# 1. Define Kubernetes CRDs
---
# define adapter 'apigee'
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: apigees.config.istio.io
  labels:
    package: apigee
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: apigee
    plural: apigees
    singular: apigee
  scope: Namespaced
  version: v1alpha2
---
# define template 'auth'
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: auths.config.istio.io
  labels:
    package: auth
    istio: mixer-instance
spec:
  group: config.istio.io
  names:
    kind: auth
    plural: auths
    singular: auth
  scope: Namespaced
  version: v1alpha2

---
# 2. Create apigee handler for edgex01 / test
apiVersion: "config.istio.io/v1alpha2"
kind: apigee
metadata:
  name: apigee-handler
  namespace: istio-system
spec:
  apid_base: http://apid:9000
  org_name: edgex01
  env_name: test
