# Define Kubernetes CRDs
# No custom configuration necessary
---
# define adapter 'apigee'
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: apigees.config.istio.io
  labels:
    package: apigee
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: apigee
    plural: apigees
    singular: apigee
  scope: Namespaced
  version: v1alpha2
---
# define template 'auth'
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: auths.config.istio.io
  labels:
    package: auth
    istio: mixer-instance
spec:
  group: config.istio.io
  names:
    kind: auth
    plural: auths
    singular: auth
  scope: Namespaced
  version: v1alpha2
