# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run: INSTALL_PROTOC=1 ./install/local_install.sh

  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: ./install/install_protoc.sh
      - run: dep ensure
      - run: go generate ./...
      - run: go test ./...

  build-image:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run: INSTALL_PROTOC=1 ./install/local_install.sh
      - run: GCP_PROJECT=apigee-api-management-istio ./install/build_mixer_docker.sh

workflows:
  version: 2
  on-commit:
    jobs:
      - build
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - test
      - build-image:
          requires:
            - build
            - test
