# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run: ./install/install_protoc.sh
      - run: ls -R /go/src/github.com/apigee | grep -v vendor
      - run: ./install/local_install.sh

  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run: go test ./...

  build-image:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run: export GCP_PROJECT=apigee-api-management-istio
      - run: ./install/build_mixer_docker.sh

workflows:
  version: 2
  on-commit:
    jobs:
      - build
      - test:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image:
          requires:
            - test
