# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run:
          command: INSTALL_PROTOC=1 ./bin/local_install.sh
          name: Run local install script
        # test needs dep ensure to be run again, since the Mixer plugin install
        # will have removed the vendor link.
      - run: dep ensure
      - run:
          command: go test -coverprofile=coverage.txt ./...
          name: Run tests
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          name: upload codecov

  build-test-image:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - run:
          command: INSTALL_PROTOC=1 ./bin/local_install.sh
          name: Run local install script
        # test needs dep ensure to be run again, since the Mixer plugin install
        # will have removed the vendor link.
      - run: dep ensure
      - run:
          command: go test -coverprofile=coverage.txt ./...
          name: Run tests
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          name: upload codecov
      - setup_remote_docker
      - run:
          command: ./bin/install_docker.sh
          name: Install docker
      - run:
          command: ./bin/install_gcloud.sh
          name: Install gcloud
      - run:
          command: GCP_PROJECT=apigee-api-management-istio MAKE_PUBLIC=1 TARGET_DOCKER_IMAGE=gcr.io/apigee-api-management-istio/istio-mixer:latest ./bin/build_mixer_docker.sh
          name: Build and push Docker image with tag latest

  build-nightly:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/apigee/istio-mixer-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: INSTALL_PROTOC=1 ./bin/local_install.sh
          name: Run local install script
      - run:
          command: ./bin/install_docker.sh
          name: Install docker
      - run:
          command: ./bin/install_gcloud.sh
          name: Install gcloud
      - run:
          command: GCP_PROJECT=apigee-api-management-istio MAKE_PUBLIC=1 TARGET_DOCKER_IMAGE=gcr.io/apigee-api-management-istio/istio-mixer:nightly ./bin/build_mixer_docker.sh
          name: Build and push Docker image with tag nightly

workflows:
  version: 2
  on-commit:
    jobs:
      - build-test-image:
          filters:
            branches:
              only: master
      - build-and-test:
          filters:
            branches:
              ignore: master
  nightly:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-test-image
      - build-nightly:
          requires:
            - build-test-image
