---
# Define an Istio API
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpec
metadata:
  creationTimestamp: null
  name: helloworld
  namespace: default
spec:
  apiKeys: # populate request.api_key attr from query param "apikey" or header "x-api-key"
  - query: apikey
  - header: x-api-key
  attributes:
    attributes:
      api.service: helloworld
      api.version: "1.0.0"
  patterns:
    # example: if method=GET & path matches /somepath, override api.operation to /otherpath
  - attributes:
      api.operation: /hello
  httpMethod: GET
  uriTemplate: /api/pets
---
# Bind the Istio API to Istio services
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpecBinding
metadata:
  creationTimestamp: null
  name: helloworld-binding
  namespace: default
spec:
  api_specs:
  - name: helloworld
    namespace: default
  services:
  - name: helloworld
    namespace: default
