# Define Kubernetes CRDs
# No custom configuration necessary
---
# define adapter 'apigee'
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: apigees.config.istio.io
  labels:
    package: apigee
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: apigee
    plural: apigees
    singular: apigee
  scope: Namespaced
  version: v1alpha2
---
# define template 'analytics'
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: analytics.config.istio.io
  labels:
    package: analytics
    istio: mixer-instance
spec:
  group: config.istio.io
  names:
    kind: analytics
    plural: analytics
    singular: analytics
  scope: Namespaced
  version: v1alpha2
