---
# Define an Istio Auth Policy
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata:
  name: auth-spec
  namespace: default
spec:
  jwts:
  - issuer: https://theganyo1-eval-test.apigee.net/istio-auth/token
    audiences:
    - microgateway
    jwks_uri: https://theganyo1-eval-test.apigee.net/istio-auth/jwkPublicKeys
---
# Bind Istio Auth Policy to services
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: auth
  namespace: default
spec:
  policies:
  - name: auth-spec
    namespace: default
  services:
  - name: helloworld    # bound to target service helloworld
    namespace: default
